import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Transformer } from 'markmap-lib';

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DIST = join(ROOT, 'dist');

/**
 * @param {string} pkg
 * @param {string} relPath
 * @returns {string}
 */
export function readPkgFile(pkg, relPath) {
  let dir = dirname(require.resolve(pkg));
  while (!existsSync(join(dir, 'package.json'))) {
    const parent = dirname(dir);
    if (parent === dir) throw new Error(`Cannot find package root for ${pkg}`);
    dir = parent;
  }
  return readFileSync(join(dir, relPath), 'utf8');
}

/** @param {string} spec */
export function readAssetSpec(spec) {
  const normalized = spec.replace(/^https:\/\/cdn\.jsdelivr\.net\/npm\//, '');
  const match = normalized.match(/^((?:@[^/]+\/[^/@]+|[^/@]+))(?:@[^/]+)?\/(.+)$/);
  if (!match) throw new Error(`Cannot resolve asset spec: ${spec}`);
  return readPkgFile(match[1], match[2]);
}

export function collectEmbeddedAssets() {
  const transformer = new Transformer();
  const assets = transformer.getAssets();
  /** @type {Record<string, string>} */
  const map = {
    'd3/dist/d3.min.js': readPkgFile('d3', 'dist/d3.min.js'),
    'markmap-view/dist/browser/index.js': readPkgFile(
      'markmap-view',
      'dist/browser/index.js'
    ),
  };

  for (const item of [...(assets.styles ?? []), ...(assets.scripts ?? [])]) {
    const spec = item.data?.href || item.data?.src;
    if (!spec) continue;
    const key = String(spec).replace(/^https:\/\/cdn\.jsdelivr\.net\/npm\//, '');
    if (map[key]) continue;
    try {
      map[key] = readAssetSpec(spec);
    } catch {
      // Optional plugin asset not installed locally.
    }
  }

  return map;
}

/** @param {Record<string, string>} [assetMap] */
export function writeEmbeddedAssetsModule(assetMap = collectEmbeddedAssets()) {
  mkdirSync(DIST, { recursive: true });
  const outPath = join(DIST, 'embedded-assets.mjs');
  writeFileSync(
    outPath,
    `// Generated by build-assets.mjs — do not edit.\nexport const embeddedAssets = ${JSON.stringify(assetMap)};\n`
  );
  return outPath;
}

const isMain =
  process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1]);

if (isMain) {
  const out = writeEmbeddedAssetsModule();
  console.log(`Wrote ${out}`);
}
